### ISSUE TITLE
Cannot read property '_defaults' of undefined 

### ISSUE THREAD

**Issue by clarklight** [arschmitz/jquery-mobile-datepicker-wrapper#49] opened 2014-11-11 06:04 UTC
Hi 
    I am not so sure why i have this error.  Cannot read property '_defaults' of undefined.
Been following this example http://jsbin.com/nilerequva/1/edit. And included the below in the head tag. 

<link rel="stylesheet" href="css/jquery.mobile.datepicker.css" />
<link rel="stylesheet" href="css/jquery.mobile.datepicker.theme.css" />

<script src="js/jquery.mobile.datepicker.js"></script>

Then just calling data-role="date"

**Comment by aureltime** [comment] 2014-12-31 08:06
i have the same issue

**Comment by arschmitz** [comment] 2014-12-31 13:06
@clarklight @aureltime That means your either missing a script or loading them in the wrong order. In the case of the jsbin above its wrong order http://jsbin.com/yibavuzabe/1/edit?html,js,output changes the order and fixes the issue. Also there was a css file missing that made the styling incorrect once that was fixed. Closing as not a bug

**Closed as completed by arschmitz** 2014-12-31 13:06 UTC
