### ISSUE TITLE
Set Dateformat

### ISSUE THREAD

**Issue by philipp2500** [arschmitz/jquery-mobile-datepicker-wrapper#29] opened 2014-04-11 11:28 UTC
$(function(){
$("#gebdat").date({ dateFormat: 'yy-mm-dd', maxDate: '0', minDate: new Date(1950, 1 - 1, 1) });
});

This is the code to change the shown dateformat? Because I want to display the date 2014-04-11 and not 04/11/2014.

What is wrong with my code? Pleas help.

**Comment by indrimuska** [comment] 2014-04-13 06:54
If you want to initialize the input field with non-standards parameters you have to load widgets manually.
Remove the attribute `data-role="date"` of your inputs and use js to initialize them.

``` diff
-   <input type="text" name="date" id="date" data-role="date">
+   <input type="text" name="date" id="date">
+   <script> $("#date").date({ dateFormat: 'yy-mm-dd' }); </script>
```

Look at that http://jsbin.com/indrimuska/77/edit

**Comment by indrimuska** [comment] 2014-04-14 09:54
Otherwise you can change the default options for all the datepicker inputs in your app:

``` js
$.mobile.date.prototype.options.dateFormat = "yy-mm-dd";
```

At the moment, unlike the ui-datepicker, this wrapper doesn't have support for changing default options (check for [`$.datepicker.setDefaults`](http://api.jqueryui.com/datepicker/#utility-setDefaults)).

**Comment by arschmitz** [comment] 2014-04-14 11:01
@philipp2500  the dateformate code seems to be working fine both via the options hash as @indrimuska posted above and via data option http://jsbin.com/indrimuska/81/edit so im not sure what your problem is if you could post a jsbin or jsfiddle test page demonstrating the issue id be happy to look more into it 

@indrimuska the setDefaults utility should still work ( though it currently does not ) ill look into updating this.

**Comment by arschmitz** [comment] 2014-04-14 11:20
@indrimuska ok $.datepicker.setDefaults now works

im also going to close this issue since i cant reproduce this issue if you comment with more details and how to reproduce ill gladly reopen.

**Closed as completed by arschmitz** 2014-04-14 11:20 UTC

**Comment by indrimuska** [comment] 2014-04-14 11:54
@philipp2500, as @arschmitz already said, I think that the best solution is to use the data-attribute:

``` js
data-date-format="yy-mm-dd"
```

@arschmitz yes, now `$.datepicker.setDefaults` works perfectly.
I just notice that this mobile-datepicker doesn't have a setDefatults wrapper like `$.date.setDefaults` or `$.mobile.date.setDefaults`, because it doesn't have a date functionality (`$.fn.date` or something similar). I know that it's not an issue, it's just an observation.

**Comment by arschmitz** [comment] 2014-04-14 11:55
@indrimuska thats correct all the utility functions are not wrapped because there is no need the regular datepicker ones should still work fine

**Comment by indrimuska** [comment] 2014-04-14 11:57
@arschmitz ok thanks.

**Comment by philipp2500** [comment] 2014-04-15 08:29
@indrimuska and @arschmitz   data-date-format="yy-mm-dd" works fine but when the page is submited with a normal form the datepicker can not change the date anymore.

**Comment by indrimuska** [comment] 2014-04-15 09:07
@philipp2500 take a look at #26

**Comment by philipp2500** [comment] 2014-04-15 12:26
@indrimuska  thx you!!
