### ISSUE TITLE
Performance issue?

### ISSUE THREAD

**Issue by tyrex1975** [arschmitz/jquery-mobile-datepicker-wrapper#39] opened 2014-05-21 10:22 UTC
I know the lack of including any Fiddle won't go down well around here, but I thought I'd bring this strange issue to your attention.

I am generating this datepicker dynamically using the code:

```
$('<input>')
.attr({
    'type': 'text',
    'id': id,
    'name': id,
    'placeholder': 'DDMMYYYY',
    'data-inline': 'false',
    'data-role': 'date'
})
.on('input', update_form) // refreshes various elements on my page after the user changes date
.date({
    firstDay: 1,
    dateFormat: 'ddmmyy'
})
```

I am making this call many times because my app requires the user to enter a date on many occasions. Unfortunately this call must be made dynamically because it isn't possible to hard-code when it is used (AJAX/JSON requests to our server determine when the date picker is required).

I have noticed that when the user has clicked the input box (which brings up the date picker) the performance of my app slows dramatically. Further clicks of the input box slows the app further until the point where it becomes unusable. It seems that it is when the datepicker is shown to the user that the performance is affected, not when the element is created using the above code.

The performance impact on desktop browsers is generally unnoticeable, however on mobile devices, such as my Lumia 1020 and iPhone 4s, it is noticeable within a couple of datepicker operations.

I tried using the following call to clear the element from the DOM, after the user has finished selecting dates to no avail:

```
$('.ui-datepicker').remove();
```

Sorry again for lack of fiddle, but any ideas?

**Comment by arschmitz** [comment] 2014-05-21 12:17
@tyrex1975 Sorry nothing comes to mind right off and with out a test case i have nothing to look at and debug. if you make a test case i am of course happy to take a look just dont have any where to go with this until i can reproduce. 

Also calling remove on the input will not remove the associated elements like the actual calendar

**Comment by arschmitz** [comment] 2014-05-21 12:18
im going to close this but will be happy to reopen if you can create a test case

**Comment by tyrex1975** [comment] 2014-05-24 17:28
Thank you and yes, I understand the problems of debugging something without a test case. Although I have not been able to create a fiddle which demonstrates the problem, I have done a LOT of further digging and found something that I thought I should bring to your attention.

On my site, it seems the performance issue is due to CPU hogging once the datepicker has been initialised and increasing once it has been used. Using the IE11 UI responsiveness tool, I've discovered that this section of code in 'jquery.mobile.datepicker.js' is running over-and-over:

```
        this._on({
          "change": function() {
            if( this.options.inline ){
              this.calendar.datepicker( "setDate", this.element.val() );
            }
            this._delay( "addMobileStyle", 10 );
          },
          "input": function() {
            interval = window.setInterval( function(){
              if( !that.calendar.hasClass( "mobile-enhanced" ) ){
                that.addMobileStyle();
              } else {
                clearInterval( interval );
              }
            });
          }
        });
```

The part that is running continuously is the function for the "input" event. On my machine it is consuming approximately 30-40% of the CPU once the datepicker has been used. Any ideas what might cause the code to run away like this?

**Comment by arschmitz** [comment] 2014-05-24 20:22
@tyrex1975 are you holding a key down lol?

Thats the event that takes place when you enter anything into a text field. Does the style look correct? it kinda sounds like the style is never getting added for some reason and so this keeps running attempting to add it. This is most likely caused by something wrong in your markup so the style is attempting to add to nothing or the wrong thing or something. 

This is also probably why you cannot reproduce in jsfiddle or jsbin.

Edit: Looking back at your original code snippit `.on('input', update_form) // refreshes various elements on my page after the user changes date` I'm going to bet this is the source of the problem

**Comment by indrimuska** [comment] 2014-05-24 21:24
@tyrex1975 is right, the `window.setInterval` on the on-input callback never clear itself, you can check it by adding `console.log('fire')` before the if-statement. I'm working on a test.

**Comment by indrimuska** [comment] 2014-05-24 21:36
I copied the original script and I add this line:

``` js
var DEBUG = 0;
```

and this one just after `interval = window.setInterval( function(){`:

``` js
$('#debug').text(++DEBUG);
```

---

Et voilà: http://jsbin.com/indrimuska/103/edit

**Comment by indrimuska** [comment] 2014-05-24 22:00
I think that it could be resolved by replacing the `setInterval` function with a simple `setTimeout` function. I don't know why the callback needs to be fired each interval.

**Closed as completed** 2014-05-24 22:03 UTC

**Comment by indrimuska** [comment] 2014-05-24 22:05
The last update doesn't resolve the issue, I see the problem, yet :(

**Comment by arschmitz** [comment] 2014-05-24 22:07
i think you should check again this completely removed the setInterval so its not possible for it to be called

**Comment by indrimuska** [comment] 2014-05-24 22:09
Yes, I'm sorry, this issue is solved, but mobile style doesn't show correctly.

**Comment by arschmitz** [comment] 2014-05-24 22:22
@indrimuska yes i just forced an update to that commit to reflect what i actually said i was doing in the commit message ie: switching to keyup vs input

**Comment by indrimuska** [comment] 2014-05-24 22:25
Yeah, keyup is the solution! :+1: 
In this case you can remove the on-change callback.

**Comment by arschmitz** [comment] 2014-05-24 22:27
nope they server different purpose change can be fired independent of the keyboard

**Comment by indrimuska** [comment] 2014-05-24 22:29
D'oh, you're right!

**Comment by arschmitz** [comment] 2014-05-24 22:29
@indrimuska see http://jsbin.com/gumor/1/edit use the menu and past in some text no keyup event occurs but a change event still does

**Comment by tyrex1975** [comment] 2014-05-24 22:58
Works perfect for me - thank you all very much :)
