### ISSUE TITLE
inputs are "disabled" after ajax reload

### ISSUE THREAD

**Issue by santaclaus21** [arschmitz/jquery-mobile-datepicker-wrapper#26] opened 2014-04-02 19:40 UTC
data-role="date" in form data-ajax="true".

After page reload (pageinit) input fields stay with send by ajax date. Dates can't be changed. I can't find a solution. 

temporary: http://24test.jordan.pl/hotele-Krakow/Galaxy/m

So, where is a problem? Without ajax everything is working fine. But I want to use it with ajax. Any help?

**Comment by arschmitz** [comment] 2014-04-02 20:28
Can you please create a simple test case reproducing the issue in jsbin you can use this as a template http://jsbin.com/ofuhaw/1/edit i cant really tell exactly whats going on from your test page its too hard to read your source. One thing i did notice is lots of duplicate id problems try fixing these and it might help.

**Comment by santaclaus21** [comment] 2014-04-02 21:23
I will do it tommorow. In case of my url - just change dates, submit form (green button "sprawdź"), then try to change dates again. It's not possible. Datepicker doesn't update input fields.

**Comment by santaclaus21** [comment] 2014-04-03 07:15
something like this, but I don't know how to set "action" on form do send it like "server.request.url" (self) in jsbin. http://jsbin.com/ofuhaw/1307/edit

**Comment by arschmitz** [comment] 2014-04-03 12:09
you are not using any code from this repository you are using a fork

**Comment by santaclaus21** [comment] 2014-04-03 12:22
changed. I don't know how to do action to send form self on jsbin... First link send by me don't use datepicker for now. Try to make any form with data-ajax="true" and datepickermobile, then send it to self page. And there is no possibility to change dates longer. I've used lates liberaries....

**Comment by arschmitz** [comment] 2014-04-03 12:32
the problem is you have duplicate id's when you self submit that way you are reloading the same page but because this is also your initial page it is not removed and is hidden in the dom ( this is how jquery mobile works nothing to do with datepicker ) so when the new page loads the datepickers are still looking for the same id in the input to update but that input is on a different page ( note it is not valid to ever have 2 elements in the dom with the same id at the same time this will lead to unexpected behavior )

To work around this you can not use ids on the input or not self submit.

im going to close this as not a bug.

**Closed as completed by arschmitz** 2014-04-03 12:32 UTC

**Comment by santaclaus21** [comment] 2014-04-03 12:51
I'm not how ajax is working in jquery mobile. But when you are doing ajax load by jquery... $('#container').load('self_url' + #container > *) DOM structure is only updated not duplicated in hidden content. So in that that case in jquery (not mobile) after ajax success I'm doing $('.date').datepicker(), and everything is working fine. In case of jquery mobile + datepicker, datepicker is launched correctly (once) even if you said id is duplicated. I'm not pretty sure that you have right.

Additional, datebox is working fine as you can see now on: http://24test.jordan.pl/hotele-Krakow/Galaxy/m. So, please check it twice. Thanks!

**Comment by arschmitz** [comment] 2014-04-03 13:00
I think you need to read more on how pages work in jQuery mobile http://demos.jquerymobile.com/1.4.2/pages/ and the ajax process we are not just replacing content as you seem to do in your example. as far as date box this is a completely different widget and i dont know how they work but the id issue is not this wrapper is how the actual jquery ui datepicker works with input id's. also duplicate id's are NEVER valid they may happen to work in some situations however that does not make them valid and they will lead to unexpected behavior and i have no intention of attempting to support invalid markup like duplicate id's.

**Comment by santaclaus21** [comment] 2014-04-03 13:10
So, why after ajax send form I can't find anything duplicated in console (source)? Additional in showed page, by onpageinit I call alert($('#data_od').length); show always 1 even if I send form (ajax method) a few times?

**Comment by indrimuska** [comment] 2014-04-03 13:51
@santaclaus21 maybe you haven't totally understand what @arschmitz is saying to you.
When JQM loads a page in ajax it just catch the content of the `div` with `data-role="page"`. If you load the same page obviously all the tag with a prefixed ID are injected inside the DOM. The result is that you will have two instances of the same page and with the same ID.

Try removing the `id` attribute on all the inputs:

``` html
<form method="get" data-ajax="true">
    <input type="text" name="from" data-role="date" value="<?=$_GET['from']?>" />
    <input type="text" name="to" data-role="date" value="<?=$_GET['to']?>" />
    <button type="submit">submit</button>
</form>
```

I think that the best solution for you rapplication is to stop ajax loading after submitting with `event.preventDefault()` and to get the results manually with an `$.ajax(...)` call.

**Comment by santaclaus21** [comment] 2014-04-03 14:04
I will try to do in that way. Thanks ! OK, now I understand JQM ajax. I've traced console while sending form with ajax method... Thanks again for help and understanding.
